# Generated by Django 5.2.3 on 2025-06-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallToAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                (
                    "link_text",
                    models.CharField(
                        help_text="The text to display on the button, e.g. 'Find out more'",
                        max_length=50,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(blank=True, help_text="An external URL to link to."),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="An internal page to link to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call to Action",
                "verbose_name_plural": "Calls to Action",
            },
        ),
    ]
