# Generated by Django 5.2.3 on 2025-06-22 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertBannerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable or disable the alert banner across the site",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="The message to display in the alert banner",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("danger", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        help_text="The type of alert to display",
                        max_length=20,
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional text for the call-to-action button",
                        max_length=50,
                    ),
                ),
                (
                    "button_external_url",
                    models.URLField(blank=True, help_text="Optional external URL to link to"),
                ),
                (
                    "button_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional internal page to link to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
