# Generated by Django 5.2.3 on 2025-06-23 17:38

import django.db.models.deletion
from django.db import migrations, models

import brownsea.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_add_alert_banner"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The author's name", max_length=255),
                ),
                (
                    "role",
                    models.TextField(blank=True, help_text="The author's role or title"),
                ),
                (
                    "profile_picture",
                    models.ForeignKey(
                        blank=True,
                        help_text="An optional profile picture for the author",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
            bases=(brownsea.core.models.BrownseaPreviewableMixin, models.Model),
        ),
    ]
