# Generated by Django 5.2.17 on 2026-08-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_page_magic_link"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("purple", "Purple"),
                            ("teal", "Teal"),
                            ("red", "Red"),
                            ("pink", "Pink"),
                            ("green", "Green"),
                            ("navy", "Navy"),
                            ("blue", "Blue"),
                            ("yellow", "Yellow"),
                        ],
                        default="white",
                        help_text="Scout brand colour for the navigation bar and primary buttons. White keeps a light navigation bar with purple buttons.",  # noqa: E501
                        max_length=20,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
