# Generated by Django 5.2.17 on 2026-08-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_theme_settings"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="themesettings",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Replaces the default Scout logo and unit name in the navigation bar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="themesettings",
            name="unit_name",
            field=models.CharField(
                default="Brownsea CMS",
                help_text="Shown under the Scout logo in the navigation bar. Not used if a custom logo is uploaded.",
                max_length=255,
                verbose_name="Unit name",
            ),
        ),
        migrations.AlterField(
            model_name="themesettings",
            name="colour",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("purple", "Purple"),
                    ("navy", "Navy"),
                    ("blue", "Blue"),
                    ("red", "Red"),
                ],
                default="white",
                help_text="Scout brand colour for the navigation bar and primary buttons. White keeps a light navigation bar with purple buttons.",  # noqa: E501
                max_length=20,
            ),
        ),
    ]
