version: "3.7"

services:
  app:
    build:
      context: .
    image: brownsea
    command: ./docker/start.sh
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://brownsea:brownsea@db:5432/brownsea
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=brownsea
      - POSTGRES_USER=brownsea
      - POSTGRES_PASSWORD=brownsea

volumes:
  postgres_data: