# Generated by Django 5.2.3 on 2026-02-06 19:42

import django.db.models.deletion
from django.db import migrations, models

import brownsea.core.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField()),
                ("body", brownsea.core.utils.StreamField(block_lookup={})),
                (
                    "quick_links",
                    brownsea.core.utils.StreamField(
                        blank=True,
                        block_lookup={},
                        help_text="Quick links to display in the sidebar",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
