# Generated by Django 5.2.17 on 2026-08-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_add_page_access_level"),
        ("topics", "0002_add_page_access_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicpage",
            name="news_content_type_plural",
            field=models.CharField(
                blank=False,
                default="news",
                help_text="The plural name of the news content type to display in the recent news section.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="topicpage",
            name="news_index_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="news.newsindexpage",
            ),
        ),
    ]
