# Generated by Django 5.2.17 on 2026-08-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_add_page_access_level"),
        ("news", "0003_add_page_access_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="news_index_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="news.newsindexpage",
            ),
        ),
    ]
