# Generated by Django 5.2.11 on 2026-03-16 19:54

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import modelsearch.index
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_add_author_snippet"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional icon name or emoji",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Category",
                "verbose_name_plural": "Supplier Categories",
                "ordering": ["name"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="SupplierListPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField()),
            ],
            options={
                "abstract": False,
            },
            bases=(
                wagtail.contrib.routable_page.models.RoutablePageMixin,
                "wagtailcore.page",
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "recommendation_status",
                    models.CharField(
                        choices=[
                            ("preferred", "Preferred Supplier"),
                            ("approved", "Approved Supplier"),
                            ("listed", "Listed (No Official Recommendation)"),
                            ("not_recommended", "Not Recommended"),
                        ],
                        db_index=True,
                        default="listed",
                        help_text="Official district recommendation status",
                        max_length=20,
                    ),
                ),
                (
                    "recommendation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Why this supplier has this status (internal notes)",
                    ),
                ),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "review_due_date",
                    models.DateField(
                        blank=True,
                        help_text="When this recommendation should be reviewed",
                        null=True,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("primary_contact_name", models.CharField(blank=True, max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="Brief overview of what this supplier provides and why they're listed"
                    ),
                ),
                (
                    "services",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Detailed services/products offered"
                    ),
                ),
                (
                    "special_terms",
                    models.TextField(
                        blank=True,
                        help_text="Any special discounts or terms for scouts members",
                    ),
                ),
                ("has_public_liability_insurance", models.BooleanField(default=False)),
                ("insurance_details", models.TextField(blank=True)),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="Relevant certifications, accreditations, etc.",
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        auto_now_add=True,
                        help_text="When this supplier was added to the system",
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        auto_now=True, help_text="Last time any field was updated"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved/set this recommendation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_suppliers",
                        to="core.author",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="suppliers.suppliercategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "ordering": ["name"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="SupplierReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewing_group",
                    models.CharField(
                        help_text="e.g. '1st Southampton Scout Group', 'Southampton City District'",
                        max_length=255,
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        help_text="Person who submitted this review", max_length=255
                    ),
                ),
                (
                    "reviewer_email",
                    models.EmailField(
                        blank=True,
                        help_text="For follow-up questions (not displayed publicly)",
                        max_length=254,
                    ),
                ),
                ("review_date", models.DateField()),
                (
                    "service_used",
                    models.CharField(
                        help_text="What did you order/use from this supplier?",
                        max_length=255,
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        blank=True,
                        help_text="Approximately when did you use this supplier?",
                        null=True,
                    ),
                ),
                (
                    "experience_summary",
                    models.TextField(help_text="Overall summary of your experience"),
                ),
                (
                    "what_went_well",
                    models.TextField(
                        blank=True,
                        help_text="Positive aspects",
                        verbose_name="What went well",
                    ),
                ),
                (
                    "what_could_improve",
                    models.TextField(
                        blank=True,
                        help_text="Areas for improvement or concerns",
                        verbose_name="What could be improved",
                    ),
                ),
                (
                    "would_use_again",
                    models.BooleanField(
                        blank=True,
                        help_text="Would your group use this supplier again? Leave blank if unsure",
                        null=True,
                    ),
                ),
                (
                    "value_for_money",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "service_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "average_rating",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Cast(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.functions.comparison.Coalesce(
                                            "value_for_money", 0
                                        ),
                                        "+",
                                        django.db.models.functions.comparison.Coalesce(
                                            "quality_rating", 0
                                        ),
                                    ),
                                    "+",
                                    django.db.models.functions.comparison.Coalesce(
                                        "service_rating", 0
                                    ),
                                ),
                                models.FloatField(),
                            ),
                            "/",
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    models.Case(
                                        models.When(
                                            then=1.0, value_for_money__isnull=False
                                        ),
                                        default=0.0,
                                    ),
                                    "+",
                                    models.Case(
                                        models.When(
                                            quality_rating__isnull=False, then=1.0
                                        ),
                                        default=0.0,
                                    ),
                                ),
                                "+",
                                models.Case(
                                    models.When(service_rating__isnull=False, then=1.0),
                                    default=0.0,
                                ),
                            ),
                        ),
                        output_field=models.FloatField(),
                    ),
                ),
                (
                    "delivery_time_actual",
                    models.CharField(
                        blank=True,
                        help_text="How long did delivery/completion actually take?",
                        max_length=100,
                    ),
                ),
                (
                    "delivery_time_promised",
                    models.CharField(
                        blank=True, help_text="What was promised?", max_length=100
                    ),
                ),
                (
                    "approved_for_display",
                    models.BooleanField(
                        default=False,
                        help_text="Admin approval required before showing publicly",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not displayed publicly)"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Review",
                "verbose_name_plural": "Supplier Reviews",
                "ordering": ["-review_date"],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
