# Generated by Django 5.2.11 on 2026-02-07 16:28

import django.db.models.deletion
from django.db import migrations, models

import brownsea.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("standard_pages", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        help_text="An introduction to the process that will be displayed at the top of the page"
                    ),
                ),
                ("body", brownsea.core.utils.StreamField(block_lookup={})),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
