# Generated by Django 5.2.10 on 2026-01-15 11:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion", 4),
                    ("heading", 5),
                    ("text", 6),
                    ("quote", 9),
                    ("warning_callout", 12),
                    ("call_to_action", 13),
                    ("links", 20),
                    ("image", 23),
                    ("image_gallery", 25),
                    ("table", 26),
                    ("document", 27),
                ],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: ("wagtail.blocks.StructBlock", [[("sections", 3)]], {}),
                    5: ("wagtail.blocks.StructBlock", [[("heading", 0)]], {}),
                    6: ("brownsea.core.blocks.RichTextBlock", (), {}),
                    7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    8: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 7), ("author", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "A short, clearly worded heading.",
                            "required": True,
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Make the callout concise, specific and self-contained.",
                            "required": True,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 10), ("content", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("core.CallToAction",),
                        {
                            "group": "2. Callouts",
                            "icon": "megaphone",
                            "template": "components/streamfield/blocks/call_to_action_block.html",
                        },
                    ),
                    14: ("wagtail.blocks.PageChooserBlock", (), {}),
                    15: ("wagtail.blocks.StructBlock", [[("page", 14)]], {}),
                    16: ("wagtail.blocks.URLBlock", (), {}),
                    17: ("wagtail.blocks.CharBlock", (), {}),
                    18: ("wagtail.blocks.RichTextBlock", (), {}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 16), ("title", 17), ("description", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [[("page", 15), ("external_link", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small (400px)"),
                                ("medium", "Medium (600px)"),
                                ("large", "Large (800px)"),
                            ],
                            "help_text": "Choose the size that best fits your content. Small for inline images, medium for standard content, large for featured images.",  # noqa: E501
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 21), ("caption", 8), ("size", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 21), ("caption", 8)]],
                        {"min_num": 1},
                    ),
                    25: ("wagtail.blocks.StreamBlock", [[("image", 24)]], {}),
                    26: ("brownsea.core.blocks.TableBlock", (), {}),
                    27: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "group": "3. Media & Embeds",
                            "icon": "doc-full-inverse",
                            "template": "components/streamfield/blocks/document_block.html",
                        },
                    ),
                },
            ),
        ),
    ]
