# Generated by Django 5.2.3 on 2026-02-04 18:59

from django.db import migrations

import brownsea.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=brownsea.core.utils.StreamField(block_lookup={}),
        ),
    ]
