# Generated by Django 5.2.17 on 2026-08-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_fix_streamfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit"),
                    ("logged_in", "Logged in only"),
                    ("magic_link", "Magic link"),
                    ("public", "Public"),
                ],
                default="inherit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsindexpage",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("inherit", "Inherit"),
                    ("logged_in", "Logged in only"),
                    ("magic_link", "Magic link"),
                    ("public", "Public"),
                ],
                default="inherit",
                max_length=20,
            ),
        ),
    ]
