# Generated by Django 5.2.11 on 2026-03-05 13:53

import django.db.models.deletion
from django.db import migrations, models

import brownsea.core.models
import brownsea.core.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalEventCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("ics_url", models.URLField()),
            ],
            options={
                "verbose_name": "External Event Calendar",
                "verbose_name_plural": "External Event Calendars",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CalendarPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField()),
                ("body", brownsea.core.utils.StreamField(blank=True, block_lookup={})),
                (
                    "external_calendar",
                    models.ForeignKey(
                        help_text="Select an external event calendar to display",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="events.externaleventcalendar",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(brownsea.core.models.InPageNavMixin, "wagtailcore.page"),
        ),
    ]
