# Generated by Django 5.2.11 on 2026-04-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaleventcalendar",
            name="external_bearer_token",
            field=models.CharField(
                blank=True,
                help_text="Optional Bearer token to include in the Authorization header when fetching this calendar.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="externaleventcalendar",
            name="external_cors_origin",
            field=models.CharField(
                blank=True,
                help_text="Optional CORS origin to allow when fetching this calendar from an external website.",
                max_length=255,
            ),
        ),
    ]
